package:
  name: ros-galactic-urdfdom
  version: 2.3.5
source:
  git_url: https://github.com/ros2-gbp/urdfdom-release.git
  git_rev: release/galactic/urdfdom/2.3.5-1
  folder: ros-galactic-urdfdom/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - console_bridge
    - python
    - ros-galactic-console-bridge-vendor
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-tinyxml-vendor
    - ros-galactic-urdfdom-headers
    - ros2-distro-mutex 0.1 galactic
    - tinyxml
  run:
    - console_bridge
    - python
    - ros-galactic-console-bridge-vendor
    - ros-galactic-ros-workspace
    - ros-galactic-tinyxml-vendor
    - ros-galactic-urdfdom-headers
    - ros2-distro-mutex 0.1 galactic
    - tinyxml
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
