pool:
  name: Default
  demands:
  - Agent.OS -equals linux
  - Agent.OSArchitecture -equals ARM64
trigger:
- buildbranch_linux_aarch64
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-diagnostic-updater ros-galactic-geographic-msgs
          ros-galactic-rosbridge-test-msgs ros-galactic-rosapi-msgs ros-galactic-rosbridge-msgs
        DOCKER_IMAGE: condaforge/linux-anvil-aarch64
      displayName: Build ros-galactic-diagnostic-updater ros-galactic-geographic-msgs
        ros-galactic-rosbridge-test-msgs ros-galactic-rosapi-msgs ros-galactic-rosbridge-msgs
- stage: stage_1
  jobs:
  - job: stage_1_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-rosbridge-library ros-galactic-robot-localization
          ros-galactic-rosapi ros-galactic-rosbridge-server
        DOCKER_IMAGE: condaforge/linux-anvil-aarch64
      displayName: Build ros-galactic-rosbridge-library ros-galactic-robot-localization
        ros-galactic-rosapi ros-galactic-rosbridge-server
- stage: stage_2
  jobs:
  - job: stage_2_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-rosbridge-suite
        DOCKER_IMAGE: condaforge/linux-anvil-aarch64
      displayName: Build ros-galactic-rosbridge-suite
