package:
  name: ros-galactic-rmw-dds-common
  version: 1.2.1
source:
  git_url: https://github.com/ros2-gbp/rmw_dds_common-release.git
  git_rev: release/galactic/rmw_dds_common/1.2.1-2
  folder: ros-galactic-rmw-dds-common/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gmock
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-osrf-testing-tools-cpp
    - ros-galactic-performance-test-fixture
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-generators
    - ros-galactic-rosidl-runtime-cpp
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-runtime
    - ros-galactic-rosidl-runtime-cpp
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
