package:
  name: ros-galactic-std-srvs
  version: 2.2.4
source:
  git_url: https://github.com/ros2-gbp/common_interfaces-release.git
  git_rev: release/galactic/std_srvs/2.2.4-1
  folder: ros-galactic-std-srvs/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-lint-common
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-generators
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-runtime
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
