package:
  name: ros-galactic-rmw-implementation
  version: 2.4.1
source:
  git_url: https://github.com/ros2-gbp/rmw_implementation-release.git
  git_rev: release/galactic/rmw_implementation/2.4.1-3
  folder: ros-galactic-rmw-implementation/src/work
  patches:
    - patch/ros-galactic-rmw-implementation.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-performance-test-fixture
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw
    - ros-galactic-rmw-connextdds
    - ros-galactic-rmw-fastrtps-cpp
    - ros-galactic-rmw-fastrtps-dynamic-cpp
    - ros-galactic-rmw-implementation-cmake
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw-connextdds
    - ros-galactic-rmw-fastrtps-cpp
    - ros-galactic-rmw-fastrtps-dynamic-cpp
    - ros-galactic-rmw-implementation-cmake
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
