package:
  name: ros-galactic-geographic-msgs
  version: 1.0.4
source:
  git_url: https://github.com/ros2-gbp/geographic_info-release.git
  git_rev: release/galactic/geographic_msgs/1.0.4-5
  folder: ros-galactic-geographic-msgs/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-geometry-msgs
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-generators
    - ros-galactic-std-msgs
    - ros-galactic-unique-identifier-msgs
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-geometry-msgs
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-runtime
    - ros-galactic-std-msgs
    - ros-galactic-unique-identifier-msgs
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
