package:
  name: ros-galactic-ros2cli-common-extensions
  version: 0.1.1
source:
  git_url: https://github.com/ros2-gbp/ros2cli_common_extensions-release.git
  git_rev: release/galactic/ros2cli_common_extensions/0.1.1-2
  folder: ros-galactic-ros2cli-common-extensions/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-launch-xml
    - ros-galactic-launch-yaml
    - ros-galactic-ros-workspace
    - ros-galactic-ros2action
    - ros-galactic-ros2cli
    - ros-galactic-ros2component
    - ros-galactic-ros2doctor
    - ros-galactic-ros2interface
    - ros-galactic-ros2launch
    - ros-galactic-ros2lifecycle
    - ros-galactic-ros2multicast
    - ros-galactic-ros2node
    - ros-galactic-ros2param
    - ros-galactic-ros2pkg
    - ros-galactic-ros2run
    - ros-galactic-ros2service
    - ros-galactic-ros2topic
    - ros-galactic-sros2
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
