package:
  name: ros-galactic-ros-core
  version: 0.9.3
source:
  git_url: https://github.com/ros2-gbp/variants-release.git
  git_rev: release/galactic/ros_core/0.9.3-2
  folder: ros-galactic-ros-core/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-auto
    - ros-galactic-ament-cmake-gmock
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-ament-cmake-ros
    - ros-galactic-ament-index-cpp
    - ros-galactic-ament-index-python
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-class-loader
    - ros-galactic-common-interfaces
    - ros-galactic-launch
    - ros-galactic-launch-ros
    - ros-galactic-launch-testing
    - ros-galactic-launch-testing-ament-cmake
    - ros-galactic-launch-testing-ros
    - ros-galactic-launch-xml
    - ros-galactic-launch-yaml
    - ros-galactic-pluginlib
    - ros-galactic-rcl-lifecycle
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-lifecycle
    - ros-galactic-rclpy
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-ros2cli-common-extensions
    - ros-galactic-ros2launch
    - ros-galactic-rosidl-default-generators
    - ros-galactic-rosidl-default-runtime
    - ros-galactic-sros2
    - ros-galactic-sros2-cmake
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
