package:
  name: ros-galactic-robot-localization
  version: 3.2.4
source:
  git_url: https://github.com/cra-ros-pkg/robot_localization-release.git
  git_rev: release/galactic/robot_localization/3.2.4-1
  folder: ros-galactic-robot-localization/src/work
  patches:
    - patch/ros-galactic-robot-localization.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - boost-cpp
    - eigen
    - geographiclib-cpp
    - numpy
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-builtin-interfaces
    - ros-galactic-diagnostic-msgs
    - ros-galactic-diagnostic-updater
    - ros-galactic-geographic-msgs
    - ros-galactic-geometry-msgs
    - ros-galactic-launch-ros
    - ros-galactic-launch-testing-ament-cmake
    - ros-galactic-message-filters
    - ros-galactic-nav-msgs
    - ros-galactic-rclcpp
    - ros-galactic-rmw-implementation
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-generators
    - ros-galactic-sensor-msgs
    - ros-galactic-std-msgs
    - ros-galactic-std-srvs
    - ros-galactic-tf2
    - ros-galactic-tf2-eigen
    - ros-galactic-tf2-geometry-msgs
    - ros-galactic-tf2-ros
    - ros-galactic-yaml-cpp-vendor
    - ros2-distro-mutex 0.1 galactic
  run:
    - boost-cpp
    - eigen
    - geographiclib-cpp
    - python
    - ros-galactic-diagnostic-msgs
    - ros-galactic-diagnostic-updater
    - ros-galactic-geographic-msgs
    - ros-galactic-geometry-msgs
    - ros-galactic-message-filters
    - ros-galactic-nav-msgs
    - ros-galactic-rclcpp
    - ros-galactic-rmw-implementation
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-runtime
    - ros-galactic-sensor-msgs
    - ros-galactic-std-msgs
    - ros-galactic-std-srvs
    - ros-galactic-tf2
    - ros-galactic-tf2-eigen
    - ros-galactic-tf2-geometry-msgs
    - ros-galactic-tf2-ros
    - ros-galactic-yaml-cpp-vendor
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
