package:
  name: ros-galactic-rosidl-typesupport-cpp
  version: 1.2.1
source:
  git_url: https://github.com/ros2-gbp/rosidl_typesupport-release.git
  git_rev: release/galactic/rosidl_typesupport_cpp/1.2.1-3
  folder: ros-galactic-rosidl-typesupport-cpp/src/work
  patches:
    - patch/ros-galactic-rosidl-typesupport-cpp.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake-core
    - ros-galactic-ament-cmake-ros
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-performance-test-fixture
    - ros-galactic-rcpputils
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-runtime-c
    - ros-galactic-rosidl-runtime-cpp
    - ros-galactic-rosidl-typesupport-c
    - ros-galactic-rosidl-typesupport-fastrtps-cpp
    - ros-galactic-rosidl-typesupport-introspection-cpp
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-ament-cmake-core
    - ros-galactic-ament-index-python
    - ros-galactic-rcpputils
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-cli
    - ros-galactic-rosidl-runtime-c
    - ros-galactic-rosidl-runtime-cpp
    - ros-galactic-rosidl-typesupport-c
    - ros-galactic-rosidl-typesupport-fastrtps-cpp
    - ros-galactic-rosidl-typesupport-interface
    - ros-galactic-rosidl-typesupport-introspection-cpp
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
